language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION="Django>=1.5,<1.6"
  - DJANGO_VERSION="https://www.djangoproject.com/download/1.6c1/tarball/#md5=7f82bfcde72ec63d7ccdff8d1369369d"

install:
  - pip install -q $DJANGO_VERSION django-mptt Pillow feedparser --use-mirrors
  - python setup.py -q install
script: "cd tests && ./manage.py test testapp"
