language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO_VERSION=1.5.5
  - DJANGO_VERSION=1.6c1
install:
  - pip install -q https://www.djangoproject.com/download/$DJANGO_VERSION/tarball/ django-mptt Pillow feedparser
  - python setup.py -q install
script: "cd tests && ./manage.py test testapp"
